DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE messages (
 sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 recipient_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 messages TEXT NOT NULL
);
